### ISSUE TITLE
Missing key in manage postgresql resource

### ISSUE THREAD

**Issue by ilya-ilya** [yandex-cloud/terraform-provider-yandex#405] opened 2023-12-26 10:03 UTC
Despite it is [available](https://cloud.yandex.ru/ru/docs/managed-postgresql/api-ref/Cluster/update) through mdb postgresql update rest api call, one cannot set key `max_standby_archive_delay` with terraform provider. For example, planning with
```
    postgresql_config = {
        max_standby_streaming_delay = 900000
        max_standby_archive_delay   = 900000
    }
```
ends with following error: `Error: Unsupported key config.0.postgresql_config.max_standby_archive_delay`.

**Comment by Denchick** [comment] 2024-01-30 05:50
Hi @ilya-ilya ! Thank you for your report!
I have a look and try to create postgresql with this config myself, and I have no problems. 
Could you please provider me more information: which PostgreSQL version and yandex-cloud provider version do you use?

**Comment by Denchick** [comment] 2024-12-18 12:37
Hi! Unfortunately, I couldn't reproduce this problem. Since there have been no new messages here for a very long time, I will close this issue.

**Closed as completed** 2024-12-18 12:57 UTC
