### ISSUE TITLE
MongoDB cluster name issue

### ISSUE THREAD

**Issue by endava-lutanase** [yandex-cloud/terraform-provider-yandex#173] opened 2021-06-16 07:43 UTC
Hello,

I am using the latest Yandex latest provider 0.59.0 and I am having the following issue / use case:

Once a MongoDB cluster is being restored from a backup in Yandex Cloud UI, and I want to change through Terraform the name of the backup restoration, it shows that the apply will change the name and that it was applied successfully, but it does not change the cluster name.

**Comment by apilikov** [comment] 2021-08-10 14:31
Thanks for reaching out! You'll get notified once this is resolved.

**Comment by kronwerk** [comment] 2021-11-19 15:08
should be fixed in upcoming v0.67.0

**Comment by apilikov** [comment] 2021-12-14 16:22
The issue has been resolved recently. Feel free to reopen if the problem is still there. Thank you!

**Closed as completed by apilikov** 2021-12-14 16:22 UTC
Labels: mdb, scheduled
