### ISSUE TITLE
terraform plan shows 'user' in postgresql resource to change even if nothing is changed

### ISSUE THREAD

**Issue by yuanlinios** [yandex-cloud/terraform-provider-yandex#90] opened 2020-07-04 11:50 UTC
It is a plain simple postgresql resource:
 
```
resource "yandex_mdb_postgresql_cluster" "pg" {
  name        = "pg"
  environment = "PRODUCTION"
  network_id  = var.vpc_id

  config {
    version = 10
    resources {
      resource_preset_id = "b1.medium"
      disk_type_id       = "network-ssd"
      disk_size          = 10
    }
    backup_window_start {
      hours = 0
      minutes = 0
    }
  }
  database {
    name  = "sample"
    owner = var.user
  }

  user {
    name     = var.user
    password = var.user_password
  }

  host {
    zone      = var.az
    subnet_id = var.subnet_id
  }
}

```

With `terraform plan` and `terraform apply` the postgresql cluster is created successfully. But when I run `terraform plan` again (without any change), it shows

```
... omit other output

      - user {
          - grants   = [] -> null
          - login    = true -> null
          - name     = "user" -> null
          - password = (sensitive value)

          - permission {
              - database_name = "sample" -> null
            }
        }
      + user {
          + grants   = []
          + login    = true
          + name     = "user"
          + password = (sensitive value)

          + permission {
              + database_name = (known after apply)
            }
        }

Plan: 0 to add, 1 to change, 0 to destroy.

```

It plans to recreate my user even if nothing is changed. I am a little puzzled about this behavior.

Yandex provider version: v0.41.1

**Comment by asalimonov** [comment] 2020-07-08 10:01
Hello @yuanlinios,
Thank you for the bug report. The issue is in invalid comparison of states (diff). We are going to fix it in the next sprint. The fixed version of the provider will be available approximately in two weeks.

**Comment by GennadySpb** [comment] 2020-08-31 10:51
@yuanlinios Hi!
Is your problem solved in the current release?

**Comment by tazhate** [comment] 2020-09-03 12:32
We are also affected. Is fix ready?

**Comment by Wolfeg** [comment] 2021-02-06 15:53
готов ли фикс? та же история если удалять/добавлять пользователей, просто происходит смещение, это очень критично

**Comment by Wolfeg** [comment] 2021-02-06 18:05
> @yuanlinios Hi!
> Is your problem solved in the current release?

version 0.50.0 is still affected, databases and users =
![image](https://user-images.githubusercontent.com/4620273/107126093-7338d700-68e0-11eb-8d5b-b2fde7e40c5c.png)

**Comment by Wolfeg** [comment] 2021-02-06 18:07
базы и пользователи создаются через dynamic блоки
![image](https://user-images.githubusercontent.com/4620273/107126153-c90d7f00-68e0-11eb-9016-5aace6fc116f.png)

**Comment by Wolfeg** [comment] 2021-02-06 19:08
в tfstate все сохраняется в виде списка
```
"user": [
              {
                "conn_limit": 30,
                "grants": [],
                "login": true,
                "name": "<user>",
                "password": "<pass>",
                "permission": [
                  {
                    "database_name": "<dbname>"
                  }
                ],
                "settings": {}
              },
              {
                "conn_limit": 30,
                "grants": [],
                "login": true,
                "name": "<user2>",
                "password": "<pass2>",
                "permission": [
                  {
                    "database_name": "<dbname2>"
                  }
                ],
                "settings": {}
              }
]
```

```
"database": [
              {
                "extension": [
                  {
                    "name": "pg_repack",
                    "version": ""
                  },
                  {
                    "name": "postgres_fdw",
                    "version": ""
                  }
                ],
                "lc_collate": "ru_RU.UTF-8",
                "lc_type": "ru_RU.UTF-8",
                "name": "<db1>",
                "owner": "<user1>"
              },
              {
                "extension": [
                  {
                    "name": "pg_repack",
                    "version": ""
                  },
                  {
                    "name": "postgres_fdw",
                    "version": ""
                  }
                ],
                "lc_collate": "ru_RU.UTF-8",
                "lc_type": "ru_RU.UTF-8",
                "name": "<db2>",
                "owner": "<user2>"
              }
]
```

**Comment by apilikov** [comment] 2021-03-05 08:50
Thanks for reaching out. Do you still experience troubles with the issue with the latest provider?

**Comment by apilikov** [comment] 2021-04-13 07:41
Closing the issue as there is no updates for a long time.

**Closed as completed by apilikov** 2021-04-13 07:41 UTC
Labels: mdb, investigating
