### ISSUE TITLE
Changing platform_id of instance forces recreation of resource

### ISSUE THREAD

**Issue by Nyoroon** [yandex-cloud/terraform-provider-yandex#11] opened 2019-04-23 13:20 UTC
But it shouldn't.
```
platform_id:                        "standard-v1" => "standard-v2" (forces new resource)
```

**Comment by GennadySpb** [comment] 2019-04-23 20:14
Hello! 

It's by design. Check this [doc](https://cloud.yandex.com/docs/compute/concepts/vm-platforms).

**Comment by Nyoroon** [comment] 2019-04-23 21:05
But recreation of resource isn't required, you can just stop instance, change platform_id and start it (just like changing cores or memory).

**Comment by GennadySpb** [comment] 2019-04-24 16:52
You right! 

Code arrived. Will be included in the next release.

**Comment by GennadySpb** [comment] 2019-04-25 07:37
Version **0.5.2** released.

**Closed as completed by GennadySpb** 2019-04-25 07:37 UTC
